services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-app
    restart: always
    environment:
      - N8N_EDITOR_BASE_URL=https://n8n.dulziasalamanca.es/
      - N8N_HOST=n8n.dulziasalamanca.es
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.dulziasalamanca.es/
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      # Desactivar secure cookie (HTTPS manejado por Cloudflare/Nginx)
      - N8N_SECURE_COOKIE=false
      # Confianza en el proxy (Nginx)
      - N8N_TRUST_PROXY=true
      # Desactivar telemetría y diagnósticos externos
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      # Autenticación básica de n8n (Capa 1 de seguridad)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      # Configuración de Base de Datos (al Postgres de Infra)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=shared-postgres-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASS}
      # Python está disponible en el contenedor (modo internal)
    volumes:
      - n8n_data:/home/node/.n8n
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - shared-network
    # Ya no hay sección 'ports'

networks:
  shared-network:
    name: shared-network
    external: true

volumes:
  n8n_data: